name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
          check-latest: true
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0